default_platform(:android)

platform :android do
  desc "link to firebase app distribution"
  lane :distribute do
    sh "cd .. && flutter clean"
    sh "cd .. && flutter pub get"
    sh "cd .. && flutter build apk --release --flavor production -t lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:895244516788:android:2e5670a484a5d47dd346e1",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      release_notes: "test link fastlane & firebase app distribution to github actions",
      testers: "malak.hayan7764@gmail.com"
    ) 
    
  end
end